spring:
  application:
    name: auth-server
  redis:
    host: 192.168.201.121
    database: 0
    port: 6389
server:
  port: 9098
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/